### ISSUE TITLE
Assuming that api-tokens will work as passwords too?

### ISSUE THREAD

**Issue by EugenMayer** [craftamap/pluploader#66]
Are there any particular reasons we do not add to the docs, that one can use the API tokens as password instead of the plain-text password of the account?

With tokens i mean those https://id.atlassian.com/manage-profile/security/api-tokens

Any thoughts?

**Comment by craftamap** [comment]
I encourage you to take a look at the created pull request #67 and see if you have any complaints. :)

**Comment by EugenMayer** [comment]
Awesome - that really helps and is the right insensitive

Thank you for being interested and responsive
